spring:
  application:
    name: api-pinal

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/pinal_db
    username: pinal
    password: passer123

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  management:
    endpoints:
      web:
        exposure:
          include:
            - health
            - info
            - flyway

  security:
    user:
      name: dev
      password: ${DEV_SECURITY_PASSWORD:passer123}
      roles:
        - PROPRIETAIRE
